### ISSUE TITLE
Download ERA data

### ISSUE THREAD

**Issue by acaruthe** [akrherz/oats#11]
We have pressure `sc` files.  We need pressure `uv` and `sfc` files. 

* [ ] ei.oper.an.pl.regn128uv.1979010100

* [ ] ei.oper.an.sfc.regn128sc.1979010100

wget $cert_opt $opts --load-cookies auth.rda.ucar.edu.$$ https://rda.ucar.edu/data/ds627.0/ei.oper.an.sfc/197901/ei.oper.an.sfc.regn128sc.1979010100

**Comment by akrherz** [comment]
Hmmmm, I am downloading these ASAP to `/mnt/nrel/akrherz/ERA_T255` post-haste

**Comment by akrherz** [comment]
Well, based on the timing found with #4, we should be done before the next new moon

**Comment by akrherz** [comment]
Download progress update

`uv` is working on May 1986, `sfc` is working on Aug 1989

**Comment by acaruthe** [comment]
peep `uv` and `sfc`download is complete

**Comment by akrherz** [comment]
Great, I have checked that
 - [x] all files are downloaded
 - [x] the `sfc` files have 48 grib messages each
 - [x] the `uv` files have 74 grib messages each
